In [1]:
import torch
print(torch.__version__)

2.9.1+cu128


In [5]:
from sympy.printing.pytorch import torch
x=torch.tensor([1,2,3,4,5])
print(x) 
y=torch.tensor([[1,2],[3,4]])
print(y)
j=torch.zeros(3,3)
print(j)
r=torch.rand(2,2)
print(r)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2],
        [3, 4]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8963, 0.5443],
        [0.4551, 0.1873]])
